version: "2"
services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./data:/data/db
  track-my-bike:
    links:
      - mongo
    environment:
      - CLIENTSECRET=6b4f5d86f8a329764290a000bc44633c26a3ab56
    build: 
       context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: bash -c "npm run webpack && npm start"