services:
  mongodb:
    image: mongo:7
    container_name: stravabikes-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - stravabikes-network

  # Optional: MongoDB Express for database management UI
  mongo-express:
    image: mongo-express:1.0
    container_name: stravabikes-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - stravabikes-network

networks:
  stravabikes-network:
    driver: bridge