import { Sequelize } from "sequelize";
export default (sequelize) => {
  sequelize.define("Activity", {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
    },
    resource_state: Sequelize.INTEGER,
    name: Sequelize.STRING,
    distance: Sequelize.INTEGER,
    moving_time: Sequelize.INTEGER,
    elapsed_time: Sequelize.INTEGER,
    total_elevation_gain: Sequelize.INTEGER,
    type: Sequelize.STRING,
    sport_type: Sequelize.STRING,
    workout_type: Sequelize.INTEGER,
    start_date: Sequelize.DATE,
    start_date_local: Sequelize.DATE,
    timezone: Sequelize.STRING,
    utc_offset: Sequelize.INTEGER,
    location_city: Sequelize.STRING,
    location_state: Sequelize.STRING,
    location_country: Sequelize.STRING,
    achievement_count: Sequelize.INTEGER,
    kudos_count: Sequelize.INTEGER,
    comment_count: Sequelize.INTEGER,
    athlete_count: Sequelize.INTEGER,
    photo_count: Sequelize.INTEGER,
    trainer: Sequelize.BOOLEAN,
    commute: Sequelize.BOOLEAN,
    manual: Sequelize.BOOLEAN,
    private: Sequelize.BOOLEAN,
    visibility: Sequelize.STRING,
    flagged: Sequelize.BOOLEAN,
    gear_id: Sequelize.STRING,
    average_speed: Sequelize.FLOAT,
    max_speed: Sequelize.FLOAT,
    average_watts: Sequelize.FLOAT,
    kilojoules: Sequelize.FLOAT,
    device_watts: Sequelize.BOOLEAN,
    has_heartrate: Sequelize.BOOLEAN,
    average_heartrate: Sequelize.FLOAT,
    max_heartrate: Sequelize.FLOAT,
    heartrate_opt_out: Sequelize.BOOLEAN,
    display_hide_heartrate_option: Sequelize.BOOLEAN,
    elev_high: Sequelize.FLOAT,
    elev_low: Sequelize.FLOAT,
    suffer_score: Sequelize.INTEGER,
    athleteId: {
      type: Sequelize.INTEGER,
      references: {
        model: "Athletes",
        key: "id",
      },
      onDelete: "set null",
    },
  });
};



